### ISSUE TITLE
request material file of the metal Ti

### ISSUE THREAD

**Issue by zmm0704** [DIDSR/MCGPU#6]
This is really an impressive job.  Then I need a material file of metal Ti now, but I can't generate it now. Can you generate it for me?

**Comment by rposer** [comment]
I found a material file on my machine which appears to be Titanium. I don't recall where I got it from. Therefore, I cannot give you any warranty that the values are correct. Hope it helps!

[titanium__5-120keV.mcgpu.gz](https://github.com/DIDSR/MCGPU/files/11397665/titanium__5-120keV.mcgpu.gz)

**Comment by zmm0704** [comment]
Thank you for your kind reply！That is helpful.

从 Windows 版邮件发送

发件人: rposer
发送时间: 2023年5月4日 20:58
收件人: DIDSR/MCGPU
抄送: zmm0704; Author
主题: Re: [DIDSR/MCGPU] request material file of the metal Ti (Issue #6)

I found a material file on my machine which appears to be Titanium. I don't recall where I got it from. Therefore, I cannot give you any warranty that the values are correct. Hope it helps!
titanium__5-120keV.mcgpu.gz

**Comment by andreubs** [comment]
You can find Titanium and other materials at the folder: https://github.com/DIDSR/MCGPU/tree/master/materials
Let me know if you need more materials. I will try to generate them faster this time.

In the following months I plan to release a new version of MCGPU (v2.0) compatible with the latest version of PENELOPE. Users will finally be able to generate their own material files in that version. I will introduce the code at the Virtual Imaging Trials in Medicine summit  (https://cvit.duke.edu/vitm24/) on April 23, in case you are interested.
