### ISSUE TITLE
Request material file for pure Iodine

### ISSUE THREAD

**Issue by rposer** [DIDSR/MCGPU#7]
First of all thanks for providing MC-GPU. It's my go-to Monte Carlo tool in most use cases. 
Would it be possible to also provide a file for pure iodine?

Thank you so much in advance!

**Comment by andreubs** [comment]
Hi rposer,

Sorry for not responding before to your ISSUE request. See if you can access the material file data in this gist: 
https://gist.github.com/andreubs/64e71f99f04a69b1d7f3a9664db117c6/raw/2b306481b36c62f06508170633a81b5d03e78748/iodine__5-120keV.mcgpu

What applications are you working on?

Andreu

**Comment by rposer** [comment]
Dear Andreu,

thank you so much for the - in my opinion - rather quick reply. I am looking into differentiating different materials in x-ray imaging. Btw, I found that for the newer materials, MC-GPU v1.3 complains about a mismatch in the number of energy bins. The newer files state there were 23002 bins. When changing the number to 23001, MC-GPU accepts them. Is this a valid workaround or will it mess up the physics models somehow? My guess is that for macroscopic applications this should have no significant effect, even if everything was shifted by one bin.

Best regards!

**Comment by andreubs** [comment]
I uploaded some new material files for MCGPU at the folder: https://github.com/DIDSR/MCGPU/tree/master/materials
Sorry for the confusion between 23001 and 23002 bins. The only difference is if the latest bin is exactly 120000 eV or 120005 eV.

In the following months I plan to release a new version of MCGPU (v2.0) compatible with the latest version of PENELOPE. Users will finally be able to generate their own material files in that version. I will introduce the code at the Virtual Imaging Trials in Medicine summit  (https://cvit.duke.edu/vitm24/) on April 23, in case you are interested.
