### ISSUE TITLE
request material file of the copper

### ISSUE THREAD

**Issue by w932908501** [DIDSR/MCGPU#9]
Hi Andreu,
Thank you so much for the MCGPU. I now need the material files for the copper, Would it be possible to also provide a file for pure copper?

**Comment by andreubs** [comment]
Looks like I missed this issue. You can find Copper and other materials at the folder: https://github.com/DIDSR/MCGPU/tree/master/materials
Let me know if you need more materials. I will try to generate them faster this time.

In the following months I plan to release a new version of MCGPU (v2.0) compatible with the latest version of PENELOPE. Users will finally be able to generate their own material files in that version. I will introduce the code at the Virtual Imaging Trials in Medicine summit  (https://cvit.duke.edu/vitm24/) on April 23, in case you are interested.
